const organisations = [
    {
        "dn": "ou=fridiks_no,ou=organisations,o=fint",
        "name": "fridiks_no",
        "orgNumber": "931388975",
        "displayName": "Frid IKS",
        "components": [],
        "legalContact": "cn=28086339155,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "fridiks.no"
    },
    {
        "dn": "ou=telemarkfylke_no,ou=organisations,o=fint",
        "name": "telemarkfylke_no",
        "orgNumber": "929882989",
        "displayName": "Telemark fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_personal,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=fint_test,ou=components,o=fint",
            "ou=kulturtanken,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=okonomi_regnskap,ou=components,o=fint"
        ],
        "legalContact": "cn=16067939755,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=19047338126,ou=contacts,o=fint",
            "cn=23069545742,ou=contacts,o=fint",
            "cn=26107444563,ou=contacts,o=fint",
            "cn=16067939755,ou=contacts,o=fint",
            "cn=24047531760,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "telemarkfylke.no"
    },
    {
        "dn": "ou=vestfoldfylke_no,ou=organisations,o=fint",
        "name": "vestfoldfylke_no",
        "orgNumber": "929882385",
        "displayName": "Vestfold fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_personal,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=fint_test,ou=components,o=fint",
            "ou=kulturtanken,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=okonomi_regnskap,ou=components,o=fint"
        ],
        "legalContact": "cn=20066725767,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=29019342709,ou=contacts,o=fint",
            "cn=16077939907,ou=contacts,o=fint",
            "cn=20066725767,ou=contacts,o=fint",
            "cn=24047531760,ou=contacts,o=fint",
            "cn=23069545742,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "vestfoldfylke.no"
    },
    {
        "dn": "ou=bfk_no,ou=organisations,o=fint",
        "name": "bfk_no",
        "orgNumber": "930580260",
        "displayName": "Buskerud fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": "cn=28086339155,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=28086339155,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "bfk.no"
    },
    {
        "dn": "ou=afk_no,ou=organisations,o=fint",
        "name": "afk_no",
        "orgNumber": "930580783",
        "displayName": "Akershus fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": "cn=28086339155,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=28086339155,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "afk.no"
    },
    {
        "dn": "ou=ofk_no,ou=organisations,o=fint",
        "name": "ofk_no",
        "orgNumber": "930580694",
        "displayName": "Østfold fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": "cn=28086339155,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=28086339155,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "ofk.no"
    },
    {
        "dn": "ou=visma_com,ou=organisations,o=fint",
        "name": "visma_com",
        "orgNumber": "936796702",
        "displayName": "visma.com",
        "components": [
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint"
        ],
        "legalContact": "cn=27077433304,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "visma.com"
    },
    {
        "dn": "ou=samediggi_no,ou=organisations,o=fint",
        "name": "samediggi_no",
        "orgNumber": "974760347",
        "displayName": "Samediggi / Sametinget",
        "components": [
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint"
        ],
        "legalContact": "cn=05088439335,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "samediggi.no"
    },
    {
        "dn": "ou=asker_kommune_no,ou=organisations,o=fint",
        "name": "asker_kommune_no",
        "orgNumber": "920125298",
        "displayName": "Asker Kommune",
        "components": [],
        "legalContact": "cn=31087246933,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "asker.kommune.no"
    },
    {
        "dn": "ou=ffk_no,ou=organisations,o=fint",
        "name": "ffk_no",
        "orgNumber": "830090282",
        "displayName": "Finnmark fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=fint_test,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": "cn=06126331523,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=06126331523,ou=contacts,o=fint",
            "cn=08106040819,ou=contacts,o=fint",
            "cn=17088338308,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "ffk.no"
    },
    {
        "dn": "ou=sfj_no,ou=organisations,o=fint",
        "name": "sfj_no",
        "orgNumber": "941388841",
        "displayName": "Sogn og Fjordane fylkeskommune",
        "components": [],
        "legalContact": "cn=27077433304,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "sfj.no"
    },
    {
        "dn": "ou=hordaland_no,ou=organisations,o=fint",
        "name": "hordaland_no",
        "orgNumber": "938626367",
        "displayName": "Hordaland fylkeskommune",
        "components": [],
        "legalContact": "cn=27077433304,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "hordaland.no"
    },
    {
        "dn": "ou=visma_enterprise_as,ou=organisations,o=fint",
        "name": "visma_enterprise_as",
        "orgNumber": "982410339",
        "displayName": "Visma Enterprise AS",
        "components": [],
        "legalContact": "cn=16107239646,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=27077433304,ou=contacts,o=fint",
            "cn=19059529792,ou=contacts,o=fint",
            "cn=28109546358,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "visma.enterprise.as"
    },
    {
        "dn": "ou=bya_oslo_kommune_no,ou=organisations,o=fint",
        "name": "bya_oslo_kommune_no",
        "orgNumber": "976819993",
        "displayName": "Oslo kommune Byantikvaren",
        "components": [
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint"
        ],
        "legalContact": "cn=08116639174,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=08116639174,ou=contacts,o=fint",
            "cn=10105334295,ou=contacts,o=fint",
            "cn=27077433304,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "bya.oslo.kommune.no"
    },
    {
        "dn": "ou=bym_oslo_kommune_no,ou=organisations,o=fint",
        "name": "bym_oslo_kommune_no",
        "orgNumber": "996922766",
        "displayName": "Oslo kommune Bymiljøetaten",
        "components": [
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=27077433304,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "bym.oslo.kommune.no"
    },
    {
        "dn": "ou=austagderfk_no,ou=organisations,o=fint",
        "name": "austagderfk_no",
        "orgNumber": "943039046",
        "displayName": "Aust-Agder fylkeskommune",
        "components": [],
        "legalContact": "cn=24078243941,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=27077433304,ou=contacts,o=fint",
            "cn=09127242566,ou=contacts,o=fint",
            "cn=15097729449,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "austagderfk.no"
    },
    {
        "dn": "ou=vaf_no,ou=organisations,o=fint",
        "name": "vaf_no",
        "orgNumber": "960895827",
        "displayName": "Vest-Agder fylkeskommune",
        "components": [],
        "legalContact": "cn=24078243941,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=24078243941,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "vaf.no"
    },
    {
        "dn": "ou=cgi_com,ou=organisations,o=fint",
        "name": "cgi_com",
        "orgNumber": "919562390",
        "displayName": "CGI Norge AS",
        "components": [
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint"
        ],
        "legalContact": "cn=05118748303,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "cgi.com"
    },
    {
        "dn": "ou=fintlabs_no,ou=organisations,o=fint",
        "name": "fintlabs_no",
        "orgNumber": "998283914",
        "displayName": "FINTLabs",
        "components": [
            "ou=felles_kodeverk,ou=components,o=fint",
            "ou=vigokodeverk,ou=components,o=fint",
            "ou=fint_metamodell,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_personal,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_larling,ou=components,o=fint",
            "ou=utdanning_ot,ou=components,o=fint"
        ],
        "legalContact": "cn=04039942939,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=05116048754,ou=contacts,o=fint",
            "cn=03027839362,ou=contacts,o=fint",
            "cn=27077433304,ou=contacts,o=fint",
            "cn=30076739974,ou=contacts,o=fint",
            "cn=07047938788,ou=contacts,o=fint",
            "cn=28066937331,ou=contacts,o=fint",
            "cn=22027835515,ou=contacts,o=fint",
            "cn=13107329263,ou=contacts,o=fint",
            "cn=24078243941,ou=contacts,o=fint",
            "cn=19078446520,ou=contacts,o=fint",
            "cn=04039942939,ou=contacts,o=fint",
            "cn=24107035504,ou=contacts,o=fint",
            "cn=11048148516,ou=contacts,o=fint",
            "cn=14120193946,ou=contacts,o=fint"
        ],
        "k8sSize": "small",
        "customer": true,
        "primaryAssetId": "fintlabs.no"
    },
    {
        "dn": "ou=lybskole_no,ou=organisations,o=fint",
        "name": "lybskole_no",
        "orgNumber": "984047851",
        "displayName": "Longyearbyen videregående skole",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=17088338308,ou=contacts,o=fint",
            "cn=10078529984,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "lybskole.no"
    },
    {
        "dn": "ou=samisk_vgs_no,ou=organisations,o=fint",
        "name": "samisk_vgs_no",
        "orgNumber": "​​​​971578807",
        "displayName": "Samisk videregående skole og reindriftsskole",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=17088338308,ou=contacts,o=fint",
            "cn=10078529984,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "samisk.vgs.no"
    },
    {
        "dn": "ou=sami_vgs_no,ou=organisations,o=fint",
        "name": "sami_vgs_no",
        "orgNumber": "971578807",
        "displayName": "Samisk Videregående Skole, Karasjok",
        "components": [
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=17088338308,ou=contacts,o=fint",
            "cn=10078529984,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "sami.vgs.no"
    },
    {
        "dn": "ou=ude_oslo_kommune_no,ou=organisations,o=fint",
        "name": "ude_oslo_kommune_no",
        "orgNumber": "976820037",
        "displayName": "Oslo kommune Utdanningsetaten",
        "components": [
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": "cn=13017133394,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=02017529741,ou=contacts,o=fint",
            "cn=23099048360,ou=contacts,o=fint",
            "cn=20126737980,ou=contacts,o=fint",
            "cn=21039041798,ou=contacts,o=fint",
            "cn=13017133394,ou=contacts,o=fint",
            "cn=27088241695,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "ude.oslo.kommune.no"
    },
    {
        "dn": "ou=dfo_no,ou=organisations,o=fint",
        "name": "dfo_no",
        "orgNumber": "986252932",
        "displayName": "DFØ",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": "cn=04117647965,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=15096027564,ou=contacts,o=fint",
            "cn=01026441745,ou=contacts,o=fint",
            "cn=04117647965,ou=contacts,o=fint",
            "cn=27077433304,ou=contacts,o=fint",
            "cn=26056531962,ou=contacts,o=fint",
            "cn=03097731933,ou=contacts,o=fint",
            "cn=22047747396,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "dfo.no"
    },
    {
        "dn": "ou=oslo_kommune_no,ou=organisations,o=fint",
        "name": "oslo_kommune_no",
        "orgNumber": "958935420",
        "displayName": "Oslo kommune",
        "components": [
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=fint_test,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=kulturtanken,ou=components,o=fint"
        ],
        "legalContact": "cn=08069341994,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=23067939719,ou=contacts,o=fint",
            "cn=23099048360,ou=contacts,o=fint",
            "cn=06027547379,ou=contacts,o=fint",
            "cn=08116639174,ou=contacts,o=fint",
            "cn=20126737980,ou=contacts,o=fint",
            "cn=05118748303,ou=contacts,o=fint",
            "cn=29028434578,ou=contacts,o=fint",
            "cn=02017529741,ou=contacts,o=fint",
            "cn=21039041798,ou=contacts,o=fint",
            "cn=08069341994,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "oslo.kommune.no"
    },
    {
        "dn": "ou=tffk_no,ou=organisations,o=fint",
        "name": "tffk_no",
        "orgNumber": "922420866",
        "displayName": "Troms og Finnmark fylkeskommune",
        "components": [
            "ou=fint_test,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint"
        ],
        "legalContact": "cn=06126331523,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=06126331523,ou=contacts,o=fint",
            "cn=10078529984,ou=contacts,o=fint",
            "cn=17088338308,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "tffk.no"
    },
    {
        "dn": "ou=arkitektum_no,ou=organisations,o=fint",
        "name": "arkitektum_no",
        "orgNumber": "914994780",
        "displayName": "Arkitektum AS",
        "components": [
            "ou=fint_test,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=27127645731,ou=contacts,o=fint",
            "cn=25078137323,ou=contacts,o=fint",
            "cn=11098941373,ou=contacts,o=fint",
            "cn=01037638559,ou=contacts,o=fint",
            "cn=27077433304,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "arkitektum.no"
    },
    {
        "dn": "ou=agderfk_no,ou=organisations,o=fint",
        "name": "agderfk_no",
        "orgNumber": "921 707 134",
        "displayName": "Agder fylkeskommune",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=okonomi_regnskap,ou=components,o=fint"
        ],
        "legalContact": "cn=15097729449,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=15097729449,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "agderfk.no"
    },
    {
        "dn": "ou=innlandetfylke_no,ou=organisations,o=fint",
        "name": "innlandetfylke_no",
        "orgNumber": "920717152",
        "displayName": "Innlandet fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=utdanning_larling,ou=components,o=fint",
            "ou=utdanning_ot,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=07096546283,ou=contacts,o=fint",
            "cn=15116431324,ou=contacts,o=fint",
            "cn=19046942577,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "innlandetfylke.no"
    },
    {
        "dn": "ou=vtfk_no,ou=organisations,o=fint",
        "name": "vtfk_no",
        "orgNumber": "821227062",
        "displayName": "Vestfold og Telemark fylkeskommune",
        "components": [
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=arkiv_personal,ou=components,o=fint",
            "ou=kulturtanken,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=fint_test,ou=components,o=fint",
            "ou=okonomi_regnskap,ou=components,o=fint"
        ],
        "legalContact": "cn=20066725767,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=27077433304,ou=contacts,o=fint",
            "cn=17126339577,ou=contacts,o=fint",
            "cn=24047531760,ou=contacts,o=fint",
            "cn=16077939907,ou=contacts,o=fint",
            "cn=13047524592,ou=contacts,o=fint",
            "cn=20066725767,ou=contacts,o=fint",
            "cn=29019342709,ou=contacts,o=fint",
            "cn=19047338126,ou=contacts,o=fint",
            "cn=23069545742,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "vtfk.no"
    },
    {
        "dn": "ou=vfk_no,ou=organisations,o=fint",
        "name": "vfk_no",
        "orgNumber": "944025391",
        "displayName": "Vestfold fylkeskommune (gammel)",
        "components": [],
        "legalContact": null,
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "vfk.no"
    },
    {
        "dn": "ou=viken_no,ou=organisations,o=fint",
        "name": "viken_no",
        "orgNumber": "921693230",
        "displayName": "Viken fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint"
        ],
        "legalContact": "cn=22019140621,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=28086339155,ou=contacts,o=fint",
            "cn=09028047824,ou=contacts,o=fint",
            "cn=28088931507,ou=contacts,o=fint",
            "cn=14047942358,ou=contacts,o=fint",
            "cn=03027839362,ou=contacts,o=fint",
            "cn=22019140621,ou=contacts,o=fint",
            "cn=11106146618,ou=contacts,o=fint",
            "cn=24046249352,ou=contacts,o=fint",
            "cn=09057928783,ou=contacts,o=fint",
            "cn=01127142048,ou=contacts,o=fint",
            "cn=26077249752,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "viken.no"
    },
    {
        "dn": "ou=vlfk_no,ou=organisations,o=fint",
        "name": "vlfk_no",
        "orgNumber": "821311632",
        "displayName": "Vestland fylkeskommune",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=arkiv_personal,ou=components,o=fint"
        ],
        "legalContact": "cn=23039040387,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=19027041178,ou=contacts,o=fint",
            "cn=05066332138,ou=contacts,o=fint",
            "cn=27107441374,ou=contacts,o=fint",
            "cn=02026632628,ou=contacts,o=fint",
            "cn=23039040387,ou=contacts,o=fint",
            "cn=30096548334,ou=contacts,o=fint",
            "cn=13047645160,ou=contacts,o=fint",
            "cn=19059646934,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "vlfk.no"
    },
    {
        "dn": "ou=tromsfylke_no,ou=organisations,o=fint",
        "name": "tromsfylke_no",
        "orgNumber": "930068128",
        "displayName": "Troms fylkeskommune",
        "components": [
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=fint_test,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": "cn=24076037902,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=10078529984,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "tromsfylke.no"
    },
    {
        "dn": "ou=ra_no,ou=organisations,o=fint",
        "name": "ra_no",
        "orgNumber": "974760819",
        "displayName": "Riksantikvaren",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint"
        ],
        "legalContact": "cn=23086847469,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=23086847469,ou=contacts,o=fint",
            "cn=27077433304,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "ra.no"
    },
    {
        "dn": "ou=nfk_no,ou=organisations,o=fint",
        "name": "nfk_no",
        "orgNumber": "964982953",
        "displayName": "Nordland fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_larling,ou=components,o=fint",
            "ou=utdanning_ot,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint"
        ],
        "legalContact": "cn=13086845134,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=27095734850,ou=contacts,o=fint",
            "cn=15127028556,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "nfk.no"
    },
    {
        "dn": "ou=trondelagfylke_no,ou=organisations,o=fint",
        "name": "trondelagfylke_no",
        "orgNumber": "817920632",
        "displayName": "Trøndelag fylkeskommune",
        "components": [
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_larling,ou=components,o=fint",
            "ou=utdanning_ot,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint"
        ],
        "legalContact": "cn=06038241301,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=06038241301,ou=contacts,o=fint",
            "cn=28069428829,ou=contacts,o=fint",
            "cn=06129022890,ou=contacts,o=fint",
            "cn=28038642199,ou=contacts,o=fint",
            "cn=11086536368,ou=contacts,o=fint",
            "cn=11127739120,ou=contacts,o=fint",
            "cn=25066844571,ou=contacts,o=fint",
            "cn=19019430351,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "trondelagfylke.no"
    },
    {
        "dn": "ou=kristiansand_kommune_no,ou=organisations,o=fint",
        "name": "kristiansand_kommune_no",
        "orgNumber": "963296746",
        "displayName": "Kristiandsand Kommune",
        "components": [
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=21047241925,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "kristiansand.kommune.no"
    },
    {
        "dn": "ou=hedmark_org,ou=organisations,o=fint",
        "name": "hedmark_org",
        "orgNumber": "942116217",
        "displayName": "Hedmark fylkeskommune",
        "components": [
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint"
        ],
        "legalContact": "cn=18127142587,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "hedmark.org"
    },
    {
        "dn": "ou=visma_no,ou=organisations,o=fint",
        "name": "visma_no",
        "orgNumber": "936796702",
        "displayName": "Visma AS",
        "components": [
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint"
        ],
        "legalContact": "cn=23058536555,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=09018727088,ou=contacts,o=fint",
            "cn=23058536555,ou=contacts,o=fint",
            "cn=26019047392,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "visma.no"
    },
    {
        "dn": "ou=evry_com,ou=organisations,o=fint",
        "name": "evry_com",
        "orgNumber": "933012867",
        "displayName": "EVRY Norge AS",
        "components": [
            "ou=fint_test,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=arkiv_personal,ou=components,o=fint",
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint"
        ],
        "legalContact": "cn=15088910386,ou=contacts,o=fint",
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "evry.com"
    },
    {
        "dn": "ou=mrfylke_no,ou=organisations,o=fint",
        "name": "mrfylke_no",
        "orgNumber": "944183779",
        "displayName": "Møre og Romsdal fylkeskommune",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_okonomi,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=betaling,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint"
        ],
        "legalContact": "cn=07117546734,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=27077433304,ou=contacts,o=fint",
            "cn=06127449307,ou=contacts,o=fint",
            "cn=24086345907,ou=contacts,o=fint",
            "cn=10057648290,ou=contacts,o=fint",
            "cn=07117546734,ou=contacts,o=fint",
            "cn=19128245793,ou=contacts,o=fint",
            "cn=15059130312,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "mrfylke.no"
    },
    {
        "dn": "ou=oppland_no,ou=organisations,o=fint",
        "name": "oppland_no",
        "orgNumber": "961382335",
        "displayName": "Oppland fylkeskommune",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint"
        ],
        "legalContact": null,
        "techicalContacts": [
            "cn=07096546283,ou=contacts,o=fint",
            "cn=27077433304,ou=contacts,o=fint",
            "cn=15116431324,ou=contacts,o=fint"
        ],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "oppland.no"
    },
    {
        "dn": "ou=rogfk_no,ou=organisations,o=fint",
        "name": "rogfk_no",
        "orgNumber": "971045698",
        "displayName": "Rogaland fylkeskommune",
        "components": [
            "ou=administrasjon_personal,ou=components,o=fint",
            "ou=utdanning_timeplan,ou=components,o=fint",
            "ou=utdanning_elev,ou=components,o=fint",
            "ou=administrasjon_kodeverk,ou=components,o=fint",
            "ou=administrasjon_organisasjon,ou=components,o=fint",
            "ou=administrasjon_fullmakt,ou=components,o=fint",
            "ou=utdanning_utdanningsprogram,ou=components,o=fint",
            "ou=utdanning_kodeverk,ou=components,o=fint",
            "ou=utdanning_vurdering,ou=components,o=fint",
            "ou=kulturtanken,ou=components,o=fint",
            "ou=fint_test,ou=components,o=fint",
            "ou=arkiv_kodeverk,ou=components,o=fint",
            "ou=arkiv_kulturminnevern,ou=components,o=fint",
            "ou=arkiv_noark,ou=components,o=fint",
            "ou=arkiv_samferdsel,ou=components,o=fint",
            "ou=okonomi_faktura,ou=components,o=fint",
            "ou=okonomi_kodeverk,ou=components,o=fint",
            "ou=profilbilde,ou=components,o=fint",
            "ou=personvern_samtykke,ou=components,o=fint",
            "ou=personvern_kodeverk,ou=components,o=fint"
        ],
        "legalContact": "cn=15046336493,ou=contacts,o=fint",
        "techicalContacts": [
            "cn=18127237774,ou=contacts,o=fint",
            "cn=27077433304,ou=contacts,o=fint",
            "cn=15046336493,ou=contacts,o=fint",
            "cn=17087344320,ou=contacts,o=fint",
            "cn=21117943930,ou=contacts,o=fint",
            "cn=06127925869,ou=contacts,o=fint",
            "cn=16068725333,ou=contacts,o=fint"
        ],
        "k8sSize": "large",
        "customer": false,
        "primaryAssetId": "rogfk.no"
    },
    {
        "dn": "ou=telemark_no,ou=organisations,o=fint",
        "name": "telemark_no",
        "orgNumber": "940192226",
        "displayName": "Telemark fylkeskommune (gammel)",
        "components": [],
        "legalContact": null,
        "techicalContacts": [],
        "k8sSize": null,
        "customer": false,
        "primaryAssetId": "telemark.no"
    }
];

export default organisations;